[project]
name = "insight-agent"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.4.3",
    "bunq-sdk>=1.28.0",
    "fastapi[standard]>=0.112.1",
    "google-genai>=1.13.0",
    "openai>=1.77.0",
]
